repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: check-xml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/maltzj/google-style-precommit-hook
    rev: 95c2f5632710e095220e22cc1a4e1a1451abf75f
    hooks:
      - id: google-style-java
